### ISSUE TITLE
Audio bug logcat

### ISSUE THREAD

**Issue by ghost** [Exynos7580/android_device_samsung_exynos7580-common#10]
Here's a full logcat using the AudioHAL variant from LineageOS ([hardware/samsung](https://github.com/LineageOS/android_hardware_samsung/)).

I think it can maybe be useful to fix the bug:
[Google Drive](https://drive.google.com/file/d/0B4zBembTERCxYnUzZ1RqcGYzZ00/view?usp=sharing)

**Comment by messi2050** [comment]
So what's the bugs with this new hall

**Comment by messi2050** [comment]
Oh i see it's completely broken..

**Comment by ghost** [comment]
It don't boot but i think we should try to adapt there new audio hal, because they are more recent and from LineageOS (i think LineageOS did a good work on this)
I'll try during the afternoon to makes this boot.
