### ISSUE TITLE
New audio hall

### ISSUE THREAD

**Issue by messi2050** [Exynos7580/android_device_samsung_exynos7580-common#12]
Guys why we are still using that old audio hall
A new one is out already
https://github.com/LineageOS/android_hardware_samsung/tree/cm-14.1/audio

**Comment by alexax66** [comment]
There is ussue with new audio hal:
`W/AudioTrack( 2743): AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 4, track 44100 Hz, output 48000 Hz`
I don't know how fix it

**Comment by Sekilsgs2** [comment]
this audio hal not working now - **raymanfx**  cant fix this .. wait him :)
