### ISSUE TITLE
Current Bugs on los 15.1

### ISSUE THREAD

**Issue by messi2050** [Exynos7580/android_device_samsung_exynos7580-common#16]
Hello 
may i know what are the current bugs on lineage 15.1

**Comment by Stricted** [comment]
audio has weird problems like calling only works with speakerphone
ril is not working for sms on the second sim on the dual sim phones
the roms are bit laggy
gps needs a lot of time to get a fix
and probably something i forgot

thats the current state of the s5 neo

**Comment by messi2050** [comment]
Ty for reporting
