### ISSUE TITLE
Codec issues causing Recorder app and Whatsapp failures 

### ISSUE THREAD

**Issue by danwood76** [Exynos7580/android_device_samsung_exynos7580-common#18]
Two issues relating to video encoding have been observed and the logcats are attached here.

They both appear to fail in a similar manner.

[ScreenRecorder-Logcat-15-03-18.txt](https://github.com/Exynos7580/android_device_samsung_exynos7580-common/files/1815727/ScreenRecorder-Logcat-15-03-18.txt)
[Whatsapp-Conversion-Logcat-15-03-18.txt](https://github.com/Exynos7580/android_device_samsung_exynos7580-common/files/1815728/Whatsapp-Conversion-Logcat-15-03-18.txt)

**Comment by messi2050** [comment]
blobs need to be updated for o

**Comment by Sekilsgs2** [comment]
what blobs? you know where problem?

**Comment by messi2050** [comment]
graphic blobs, i had simlar problem on ph2n

**Comment by Sekilsgs2** [comment]
maybe you know some info about this.. from logs i'm cant understand where problem... i'm only see -
 recorder say about wrong color format and after acodec say -  error from exynos avc...  
Graphics blobs - what graphics blobs - gralloc or omx or ?

**Comment by Sekilsgs2** [comment]
Fixed for me.. need some blobs from stock.. maybe one - libcsc.. 
But again - our and newest soc from samsung dont have gsc units! Only exynos5 have hw gsc units! gscaler and scaler not working properly for us with oss libs from exynos5.

**Comment by Sekilsgs2** [comment]
Fix this - need libcsc, gscaler and scaler from stock - not oss, because our and newest samsung soc can't have gsc units! and our scaler use /dev/m2m1shot_scaler* !
And need add this commit - https://github.com/LineageOS/android_device_samsung_universal7880-common/commit/8735125982fe6d1fb6774e0ae9f98b1809a2fbb5

**Comment by Sekilsgs2** [comment]
Other problems? Why reopen?

**Comment by Stricted** [comment]
its good that its fixed for you, since its not in the main branches its not fixed for @danwood76 yet
i preffer to keep issues open till the reporter confirms that its fixed for him

**Comment by Sekilsgs2** [comment]
ok. But you can see that some blobs needed! and no one can make better for now.

**Comment by danwood76** [comment]
@Stricted I can confirm that your latest changes fixes the issue in both apps.

Thank you all for your hard work.
