### ISSUE TITLE
BT calls not working on 15.1

### ISSUE THREAD

**Issue by Sekilsgs2** [Exynos7580/android_device_samsung_exynos7580-common#20]
With my research - this because google add esco commits which needed new fw.. 
such as this - 
https://github.com/LineageOS/android_system_bt/commit/57f6508cf7b22788fa2e7a739cec241b785718fb#diff-530543fe2fe57ff71b45d3f1d4db630f

**Comment by bunnyyTheFreak** [comment]
Did you find any fix for this?

**Comment by Sekilsgs2** [comment]
no
Some samsung have this chip.. and later have android 8 - maybe we can take blobs and put to our tree...

**Comment by bunnyyTheFreak** [comment]
Where we can find the blobs?? 
I feel something is wrong in audio hal for a5.

**Comment by Sekilsgs2** [comment]
this not problem in audio hal.

**Comment by bunnyyTheFreak** [comment]
Okay Thanks I'll find it out.

**Comment by bunnyyTheFreak** [comment]
The log says it’s unable to find path for bt, though its mentioned in the mixer path still it doesn’t finds the path. 
I have the log did try many things but neither of them worked.

**Comment by BunsExynos** [comment]
Also it says unsupported for the mic and speaker version mentioned

**Comment by bunnyyTheFreak** [comment]
[logbt.txt](https://github.com/Exynos7580/android_device_samsung_exynos7580-common/files/2512734/logbt.txt)
Here's the log

**Comment by BunsExynos** [comment]
it may be due to we force our audio hal to use wideband for calls, not sure though

**Comment by bunnyyTheFreak** [comment]
> With my research - this because google add esco commits which needed new fw..
> such as this -
> [LineageOS/android_system_bt@57f6508#diff-530543fe2fe57ff71b45d3f1d4db630f](https://github.com/LineageOS/android_system_bt/commit/57f6508cf7b22788fa2e7a739cec241b785718fb#diff-530543fe2fe57ff71b45d3f1d4db630f)


10-09 09:51:29.005  8800  8840 W bt_btm  : BTM Remote does not support 2-EDR eSCO
10-09 09:51:29.006  8800  8840 W bt_btm  : BTM Remote does not support 3-EDR eSCO

**Comment by Sekilsgs2** [comment]
i'm write again - this not problem in audiohal! audiohal working good for 14.1 LOS - in 15.1 other bluetooth stack - problem in bluetooth and only.

**Comment by bunnyyTheFreak** [comment]
> i'm write again - this not problem in audiohal! audiohal working good for 14.1 LOS - in 15.1 other bluetooth stack - problem in bluetooth and only.

I did not mention anything again about the audio hal I was saying about the bt firmware only,

**Comment by Sekilsgs2** [comment]
j610f should have same chip and have oreo.. need try bt blobs from j610f.

**Comment by danwood76** [comment]
@Sekilsgs2 I don't think the lack of eSCO is breaking BT calls.

This patch to the Bluetooth hardware interface: https://forum.xda-developers.com/showpost.php?p=78072127&postcount=934 gets us audio through the BT headset, although it is currently garbled in both directions (sounds like a bitrate mismatch).

**Comment by bunnyyTheFreak** [comment]
Danny did you try this patch??

**Comment by danwood76** [comment]
> Danny did you try this patch??

Yes, it gives call audio through the headset but the audio is garbled. This post may hold the solution to the garbled audio: https://forum.xda-developers.com/lineage/general/kb-article-troubleshooting-bluetooth-t3646969

**Comment by bunnyyTheFreak** [comment]
Cool bro I’ll try this once I’m back home thanks bro👍🏻👍🏻

**Comment by danwood76** [comment]
> Cool bro I’ll try this once I’m back home thanks bro👍🏻👍🏻

I have submitted that patch to gerrit:
https://review.lineageos.org/233817

**Comment by danwood76** [comment]
@Sekilsgs2 
It seems you were partly right about the eSCO stuff, this is the required change to disable it:
https://github.com/Exynos7580/android_device_samsung_a3xeltexx/commit/3d5b28b43f7396d74848f7ac28d089adbdcf3128
This with the previous repo pick gives working bluetooth calling on the A3.

**Comment by Sekilsgs2** [comment]
cool
Strange but i'm tring this command... maybe in other place..

**Comment by danwood76** [comment]
Looking at your branch you had:
"#define BTM_SCO_ENHANCED_SYNC_DISABLED TRUE"
Whereas the correct define is "BTM_SCO_ENHANCED_SYNC_ENABLED" with opposite logic, maybe there was a switch of logic during the code review?

Either way I have been using BT calling now for a few weeks with several different headsets/devices.
